
load("@rules_tree_sitter//tree_sitter/internal:toolchain.bzl", "tree_sitter_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

tree_sitter_toolchain_alias(
    name = "current_tree_sitter_toolchain",
    visibility = ["//visibility:public"],
)
