
name: CI

on:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rules_tree_sitter
        uses: actions/checkout@v2.3.4

      - name: Setup bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Setup node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 10.19.0

      - name: Mount the bazel cache
        uses: actions/cache@v2.1.6
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Run tests
        run: |
          node --version
          bazelisk test --build_tests_only //tests
