
name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rules_tree_sitter
        uses: actions/checkout@v2.3.4

      - name: Setup bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Mount the bazel cache
        uses: actions/cache@v2.1.6
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Run tests
        run: |
          bazelisk test --build_tests_only //tests
